#!/usr/bin/env bash

HIPACHE_CONTAINER=$(docker ps | grep hipache | cut -d" " -f1)
RETHINK_CONTAINER=$(docker ps | grep 'registry.stinemat.es/keeb/rethink' | cut -d" " -f1)

if [[ -z "$HIPACHE_CONTAINER" ]]; then
    echo "hipache is not running"
    exit 1
fi

if [[ -z "$RETHINK_CONTAINER" ]]; then
    echo "rethink is not running"
    exit 1
fi

HOST=172.17.42.1
RELAYR_DOMAIN=relayr

RETHINK_PORT=$(docker port $RETHINK_CONTAINER 28015)
REDIS_PORT=$(docker port $HIPACHE_CONTAINER 6379)
REDIS_HOST=$HOST

RELAYR_CONTAINER=$(docker run -d \
    -e RETHINK_HOST=$HOST \
    -e RETHINK_PORT=$RETHINK_PORT \
    registry.stinemat.es/keeb/relayr)

RELAYR_PORT=$(docker port $RELAYR_CONTAINER 5000)
RELAYR_HOST=$HOST

# clear out old keys
redis-cli -h $REDIS_HOST -p $REDIS_PORT del frontend:$RELAYR_DOMAIN
redis-cli -h $REDIS_HOST -p $REDIS_PORT rpush frontend:$RELAYR_DOMAIN relayr
redis-cli -h $REDIS_HOST -p $REDIS_PORT rpush frontend:$RELAYR_DOMAIN http://$RELAYR_HOST:$RELAYR_PORT
